### ISSUE TITLE
Communicate size of Fedonce

### ISSUE THREAD

**Issue by huuthieu** [JerryLife/FedOnce#1]
I have been using the Fedonce project, and I've noticed that there is a lack of communication size calculation in FedOnce (your VerticalFLModel class)

**Comment by JerryLife** [comment]
The communication size is calculated based on the representation size. Would you please specifically suggest which part of communication is missing? Thanks.

**Comment by huuthieu** [comment]
@JerryLife  In your `split_nn_model.py` file, in the `SplitNNModel` class, I see the following communication size calculation:
```
                # forward propagation communication size in bytes
                self.comm_size += (model.agg_model.fc_layers[0].in_features
                                  * np.dtype(np.float32).itemsize)
```
and
```
                # backward propagation size in bytes
                self.comm_size += (np.prod(model.agg_model.fc_layers[0].weight.grad.shape) +
                                   np.prod(model.agg_model.fc_layers[0].bias.grad.shape)) \
                                   * np.dtype(np.float32).itemsize
```

But in the FedOnce and Combine model classes, which is `VerticalFLModel` and `SingleParty`, I don't see the code that calculates the communication size. I wonder how to calculate them.

**Comment by JerryLife** [comment]
Sorry for the late reply due to my recent busy schedule. The one-shot communication size of FedOnce can be simply calculated according to the hyperparamter settings, thus not included in the training codes which mostly executed locally. Specifically, the communication of FedOnce was calculated based on the following formula.
``` 
fedonce_comm_bytes = num_train_instances * local_output_size * num_guest_parties * np.dtype(np.float32).itemsize 
```
These communication cost contains the transmitted representations of each guest party to the host party. `local_output_size` describes the dimension of the representation, which is a hyperpameter in FedOnce and SplitNN. 

Hope it clarifies. Please let me know if you have further questions.

**Comment by huuthieu** [comment]
Thanks for your answer.
